version: '3'
services:
  auth-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: AuthService
    ports:
      - "3306:3306"
