version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UserService
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  create-service:
    build: ./create-service
    ports:
      - "2001:2001"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: PropertyService

  read-service:
    build: ./read-service
    ports:
      - "2002:2002"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: UserService

  update-service:
    build: ./update-service
    ports:
      - "2003:2003"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: UserService

  delete-service:
    build: ./delete-service
    ports:
      - "2004:2004"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: UserService

volumes:
  mysql_data:
