version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PropertyService
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  create-service:
    build: ./create-service
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: PropertyService

  read-service:
    build: ./read-service
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: PropertyService

  update-service:
    build: ./update-service
    ports:
      - "3003:3003"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: PropertyService

  delete-service:
    build: ./delete-service
    ports:
      - "3004:3004"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: PropertyService

volumes:
  mysql_data:
