version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PropertyServices
    ports:
      - "3306:3306"

  create-service:
    build: ./create_property
    container_name: create-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    ports:
      - "3001:3001"

  read-service:
    build: ./read_property
    container_name: read-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    ports:
      - "3002:3002"

  update-service:
    build: ./update_property
    container_name: update-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    ports:
      - "3003:3003"

  delete-service:
    build: ./delete_property
    container_name: delete-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    ports:
      - "3004:3004"

  api-gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "80:80"
    depends_on:
      - create-service
      - read-service
      - update-service
      - delete-service
