# Usar una imagen base de Node.js
FROM node:16

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar los archivos del proyecto al contenedor
COPY package*.json ./
RUN npm install
COPY . .

# Exponer el puerto
EXPOSE 5000

# Comando para iniciar el servidor
CMD ["node", "app.js"]
