# Usa la misma versión de Go que en go.mod
FROM golang:1.21 AS builder

WORKDIR /app

# Copiar solo go.mod y go.sum primero para aprovechar la caché
COPY go.mod go.sum ./

RUN go mod download

# Copiar el resto de los archivos
COPY . .

# Compilar la aplicación (estáticamente)
RUN CGO_ENABLED=0 GOOS=linux go build -o main .


EXPOSE 3004

# Imagen final
FROM alpine:latest
WORKDIR /root/

# Copiar el binario compilado desde la etapa de construcción
COPY --from=builder /app/main .

# Dar permisos de ejecución al binario
RUN chmod +x /root/main

# Comando para ejecutar el binario
CMD ["./main"]
