# Use a Node.js base image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the application files
COPY package*.json ./
RUN npm install
COPY . .

# Expose the port on which the microservice runs
EXPOSE 5000

# Command to start the application
CMD ["node", "app.js"]
