# Use a Node.js base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the application files
COPY package.json package-lock.json ./
RUN npm install

# Copy the application files
COPY . .

# Expose the port on which the microservice runs
EXPOSE 7001

# Command to start the application
CMD ["node", "index.js"]