# Usa una imagen base de Node.js
FROM node:18

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de package.json y package-lock.json correctamente
COPY package.json package-lock.json ./

# Instala las dependencias
RUN npm install

# Copia solo la carpeta del servicio que necesitas
COPY . ./

# Expone el puerto
EXPOSE 4001

# Comando para ejecutar la aplicación
CMD ["node", "index.js"]