# Usa la misma versión de Go que en go.mod
FROM golang:1.21 AS builder

WORKDIR /app

# Copiar solo go.mod y go.sum primero para aprovechar la caché
COPY go.mod go.sum ./

RUN go mod download

# Copiar el resto de los archivos
COPY . .

# Compilar la aplicación
RUN go build -o main .

# Expone el puerto 3002
EXPOSE 3002

# Imagen final
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
CMD ["./main"]
