name: Deploy Microservice to EC2

on:
  push:
    branches:
      - Test2  

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd  
          file: ./BackEnd/Users/Students/read_student/Dockerfile  
          push: true
          tags: ksrobalino/microser-read-student:latest  

  deploy_to_ec2:
    name: Deploy Docker Container to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_image

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_CREATEUSER_TEST }}  
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Instalar Docker si no está instalado
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

            # Detener y eliminar el contenedor si ya existe
            sudo docker stop microser-read-student || true
            sudo docker rm microser-read-student || true

            # Crear un archivo .env en la instancia EC2 con las variables de entorno
            echo "DB_HOST=database-users.cge22i1wn4cz.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=Narusenin123" >> .env
            echo "DB_NAME=StudentService" >> .env
            echo "DB_PORT=3306" >> .env
            echo "PORT=6002" >> .env

            # Descargar la imagen Docker
            sudo docker pull ksrobalino/microser-read-student:latest  # Cambiado a microser-read-student

            # Ejecutar el contenedor
            sudo docker run -d --name microser-read-student --env-file .env -p 6002:6002 ksrobalino/microser-read-student:latest