name: Deploy Billing Microservices to EC2

on:
  push:
    branches:
      - Test2

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Create Invoice Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/BillingService/create_invoice
          file: ./BackEnd/BillingService/create_invoice/Dockerfile
          push: true
          tags: ksrobalino/microservicio-create-invoice:latest

      - name: Build and push Read Invoice Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/BillingService/read_invoice
          file: ./BackEnd/BillingService/read_invoice/Dockerfile
          push: true
          tags: ksrobalino/microservicio-read-invoice:latest

      - name: Build and push Update Invoice Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/BillingService/update_invoice
          file: ./BackEnd/BillingService/update_invoice/Dockerfile
          push: true
          tags: ksrobalino/microservicio-update-invoice:latest

      - name: Build and push Delete Invoice Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/BillingService/delete_invoice
          file: ./BackEnd/BillingService/delete_invoice/Dockerfile
          push: true
          tags: ksrobalino/microservicio-delete-invoice:latest

  deploy_to_ec2:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_BILLING_TEST }}  
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

          
            echo "DB_HOST=basemysql.c0koula3al44.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=Ksrobalino123" >> .env
            echo "DB_NAME=BillingServices" >> .env

           
            sudo docker stop microservicio-create-invoice microservicio-read-invoice microservicio-update-invoice microservicio-delete-invoice || true
            sudo docker rm microservicio-create-invoice microservicio-read-invoice microservicio-update-invoice microservicio-delete-invoice || true

         
            sudo docker pull ksrobalino/microservicio-create-invoice:latest
            sudo docker pull ksrobalino/microservicio-read-invoice:latest
            sudo docker pull ksrobalino/microservicio-update-invoice:latest
            sudo docker pull ksrobalino/microservicio-delete-invoice:latest

            
            sudo docker run -d --name microservicio-create-invoice --env-file .env -p 5001:5001 ksrobalino/microservicio-create-invoice:latest
            sudo docker run -d --name microservicio-read-invoice --env-file .env -p 5002:5002 ksrobalino/microservicio-read-invoice:latest
            sudo docker run -d --name microservicio-update-invoice --env-file .env -p 5003:5003 ksrobalino/microservicio-update-invoice:latest
            sudo docker run -d --name microservicio-delete-invoice --env-file .env -p 5004:5004 ksrobalino/microservicio-delete-invoice:latest