name: Deploy AuthServices to EC2

on:
  push:
    branches:
      - Test2  

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push AuthService Owners
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/AuthService_owners  
          file: ./BackEnd/AuthService_owners/Dockerfile  
          push: true
          tags: ksrobalino/microservicio-auth-owners:latest  

      - name: Build and push AuthService Student
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/AuthService_student  
          file: ./BackEnd/AuthService_student/Dockerfile  
          push: true
          tags: ksrobalino/microservicio-auth-students:latest  

  deploy_to_ec2:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_AUTHSERVICE_TEST }}  
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

            
            sudo docker stop microservicio-auth-owners microservicio-auth-students || true
            sudo docker rm microservicio-auth-owners microservicio-auth-students || true

            
            echo "DB_HOST=basemysql.c0koula3al44.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=Ksrobalino123" >> .env
            echo "DB_NAME=AuthServices" >> .env
            echo "DB_PORT=3306" >> .env
            echo "JWT_SECRET=JWT123" >> .env

            
            sudo docker pull ksrobalino/microservicio-auth-owners:latest
            sudo docker pull ksrobalino/microservicio-auth-students:latest

            
            sudo docker run -d --name microservicio-auth-owners --env-file .env -p 8000:8000 ksrobalino/microservicio-auth-owners:latest
            sudo docker run -d --name microservicio-auth-students --env-file .env -p 5020:5020 ksrobalino/microservicio-auth-students:latest