name: Deploy Student Microservices to EC2

on:
  push:
    branches:
      - Test2  

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Create Student Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Users/Students/create_student/Dockerfile
          push: true
          tags: ksrobalino/microservicio-create-student:latest

      - name: Build and push Read Student Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Users/Students/read_student/Dockerfile
          push: true
          tags: ksrobalino/microservicio-read-student:latest

      - name: Build and push Update Student Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Users/Students/update_student/Dockerfile
          push: true
          tags: ksrobalino/microservicio-update-student:latest

      - name: Build and push Delete Student Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Users/Students/delete_student/Dockerfile
          push: true
          tags: ksrobalino/microservicio-delete-student:latest

  deploy_to_ec2:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_STUDENT_TEST }}  
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

            
            echo "DB_HOST=basemysql.c0koula3al44.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=Ksrobalino123" >> .env
            echo "DB_NAME=StudentService" >> .env
            echo "DB_PORT=3306" >> .env

            
            sudo docker stop microservicio-create-student microservicio-read-student microservicio-update-student microservicio-delete-student || true
            sudo docker rm microservicio-create-student microservicio-read-student microservicio-update-student microservicio-delete-student || true

            
            sudo docker pull ksrobalino/microservicio-create-student:latest
            sudo docker pull ksrobalino/microservicio-read-student:latest
            sudo docker pull ksrobalino/microservicio-update-student:latest
            sudo docker pull ksrobalino/microservicio-delete-student:latest

            
            sudo docker run -d --name microservicio-create-student --env-file .env -p 6001:6001 ksrobalino/microservicio-create-student:latest
            sudo docker run -d --name microservicio-read-student --env-file .env -p 6002:6002 ksrobalino/microservicio-read-student:latest
            sudo docker run -d --name microservicio-update-student --env-file .env -p 6003:6003 ksrobalino/microservicio-update-student:latest
            sudo docker run -d --name microservicio-delete-student --env-file .env -p 6004:6004 ksrobalino/microservicio-delete-student:latest