name: Deploy Frontend to EC2

on:
  push:
    branches:
      - Test2  

jobs:
  build_and_push_frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./FrontEnd/residenciapp  
          file: ./FrontEnd/residenciapp/Dockerfile  
          push: true
          tags: ksrobalino/frontend-react:latest

  deploy_frontend_to_ec2:
    name: Deploy Frontend to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_frontend 

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND }}  
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Instalar Docker si no está instalado
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi  

            # Detener y eliminar el contenedor del frontend si existe.
            sudo docker stop frontend-react || true
            sudo docker rm frontend-react || true

            # Descargar la imagen más reciente del frontend
            sudo docker pull ksrobalino/frontend-react:latest

            # Ejecutar el frontend
            sudo docker run -d --name frontend-react -p 80:80 ksrobalino/frontend-react:latest