name: Deploy Payments Microservices to EC2

on:
  push:
    branches:
      - Test2  

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Generate Payments Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/Payments/generate_payments  
          file: ./BackEnd/Payments/generate_payments/Dockerfile  
          push: true
          tags: ksrobalino/generate_payments:latest  

      - name: Build and push Payments Details Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/Payments/payments_details 
          file: ./BackEnd/Payments/payments_details/Dockerfile 
          push: true
          tags: ksrobalino/payments_details:latest  

  deploy_to_ec2:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_PAYMENTS_TEST }}  
          username: ec2-user  
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

            
            echo "DB_HOST=dbpostgres.c0koula3al44.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin123" >> .env
            echo "DB_PASSWORD=Ksrobalino123" >> .env
            echo "DB_NAME=postgres" >> .env
            echo "DB_PORT=5432" >> .env

            
            sudo docker stop generate_payments payments_details || true
            sudo docker rm generate_payments payments_details || true

           
            sudo docker pull ksrobalino/generate_payments:latest
            sudo docker pull ksrobalino/payments_details:latest

            
            sudo docker run -d --name generate_payments --env-file .env -p 9002:9002 ksrobalino/generate_payments:latest
            sudo docker run -d --name payments_details --env-file .env -p 9003:9003 ksrobalino/payments_details:latest