name: Deploy Property Microservices to EC2

on:
  push:
    branches:
      - Test2  

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Create Property Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/Properties/create_property
          file: ./BackEnd/Properties/create_property/Dockerfile
          push: true
          tags: ksrobalino/microservicio-create-property:latest

      - name: Build and push Read Property Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/Properties/read_property
          file: ./BackEnd/Properties/read_property/Dockerfile
          push: true
          tags: ksrobalino/microservicio-read-property:latest

      - name: Build and push Update Property Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/Properties/update_property
          file: ./BackEnd/Properties/update_property/Dockerfile
          push: true
          tags: ksrobalino/microservicio-update-property:latest

      - name: Build and push Delete Property Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/Properties/delete_property
          file: ./BackEnd/Properties/delete_property/Dockerfile
          push: true
          tags: ksrobalino/microservicio-delete-property:latest

  deploy_to_ec2:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_PROPERTY_TEST }} 
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
          
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

        
            echo "DB_HOST=basemysql.c0koula3al44.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=Ksrobalino123" >> .env
            echo "DB_NAME=PropertyServices" >> .env
            echo "DB_PORT=3306" >> .env

          
            sudo docker stop microservicio-create-property microservicio-read-property microservicio-update-property microservicio-delete-property || true
            sudo docker rm microservicio-create-property microservicio-read-property microservicio-update-property microservicio-delete-property || true

          
            sudo docker pull ksrobalino/microservicio-create-property:latest
            sudo docker pull ksrobalino/microservicio-read-property:latest
            sudo docker pull ksrobalino/microservicio-update-property:latest
            sudo docker pull ksrobalino/microservicio-delete-property:latest

          
            sudo docker run -d --name microservicio-create-property --env-file .env -p 3001:3001 ksrobalino/microservicio-create-property:latest
            sudo docker run -d --name microservicio-read-property --env-file .env -p 3002:3002 ksrobalino/microservicio-read-property:latest
            sudo docker run -d --name microservicio-update-property --env-file .env -p 3003:3003 ksrobalino/microservicio-update-property:latest
            sudo docker run -d --name microservicio-delete-property --env-file .env -p 3004:3004 ksrobalino/microservicio-delete-property:latest