name: Deploy Owner Microservices to EC2

on:
  push:
    branches:
      - Test2  

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Create Owner Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Users/Owners/create_owner/Dockerfile
          push: true
          tags: ksrobalino/microservicio-create-owner:latest

      - name: Build and push Read Owner Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Users/Owners/read_owner/Dockerfile
          push: true
          tags: ksrobalino/microservicio-read-owner:latest

      - name: Build and push Update Owner Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Users/Owners/update_owner/Dockerfile
          push: true
          tags: ksrobalino/microservicio-update-owner:latest

      - name: Build and push Delete Owner Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Users/Owners/delete_owner/Dockerfile
          push: true
          tags: ksrobalino/microservicio-delete-owner:latest

  deploy_to_ec2:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_OWNER_TEST }} 
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

            
            echo "DB_HOST=basemysql.c0koula3al44.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=Ksrobalino123" >> .env
            echo "DB_NAME=OwnerService" >> .env
            echo "DB_PORT=3306" >> .env

            
            sudo docker stop microservicio-create-owner microservicio-read-owner microservicio-update-owner microservicio-delete-owner || true
            sudo docker rm microservicio-create-owner microservicio-read-owner microservicio-update-owner microservicio-delete-owner || true

            
            sudo docker pull ksrobalino/microservicio-create-owner:latest
            sudo docker pull ksrobalino/microservicio-read-owner:latest
            sudo docker pull ksrobalino/microservicio-update-owner:latest
            sudo docker pull ksrobalino/microservicio-delete-owner:latest

            
            sudo docker run -d --name microservicio-create-owner --env-file .env -p 7001:7001 ksrobalino/microservicio-create-owner:latest
            sudo docker run -d --name microservicio-read-owner --env-file .env -p 7002:7002 ksrobalino/microservicio-read-owner:latest
            sudo docker run -d --name microservicio-update-owner --env-file .env -p 7003:7003 ksrobalino/microservicio-update-owner:latest
            sudo docker run -d --name microservicio-delete-owner --env-file .env -p 7004:7004 ksrobalino/microservicio-delete-owner:latest