name: Deploy Microservice Update Invoice to EC2

on:
  push:
    branches:
      - Test2  

jobs:
  build_and_push_image_update_invoice:
    name: Build and Push Docker Image 
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/BillingService/update_invoice  # Ruta al microservicio
          file: ./BackEnd/BillingService/update_invoice/Dockerfile  # Ruta al Dockerfile
          push: true
          tags: ksrobalino/microservicio-update-invoice:latest  # Nombre de la imagen en Docker Hub

  deploy_to_ec2_update_invoice:
    name: Deploy Docker Container to EC2 (Update Invoice)
    runs-on: ubuntu-latest
    needs: build_and_push_image_update_invoice

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_UPDATEINVOICE }}  # Cambia esto al host de tu EC2
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

            sudo docker stop microservicio-update-invoice || true
            sudo docker rm microservicio-update-invoice || true

            # Crear el archivo .env
            echo "DB_HOST=basemysql.c0koula3al44.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=Ksrobalino123" >> .env
            echo "DB_NAME=BillingServices" >> .env
            echo "PORT=5003" >> .env

            sudo docker pull ksrobalino/microservicio-update-invoice:latest

            sudo docker run -d --name microservicio-update-invoice --env-file .env -p 5003:5003 ksrobalino/microservicio-update-invoice:latest
