name: Deploy Microservice to EC2

on:
  push:
    branches:
      - main  

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd  
          file: ./BackEnd/Users/Owners/update_owner/Dockerfile  
          push: true
          tags: ksrobalino/microservicio-update-owner:latest  

  deploy_to_ec2:
    name: Deploy Docker Container to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_image

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_UPDATEOWNER }}  
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
         
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi

          
            sudo docker stop microservicio-update-owner || true
            sudo docker rm microservicio-update-owner || true

            
            echo "DB_HOST=database-users.cge22i1wn4cz.us-east-1.rds.amazonaws.com" > .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=Narusenin123" >> .env
            echo "DB_NAME=OwnerService" >> .env  
            echo "DB_PORT=3306" >> .env
            echo "PORT=7003" >> .env  

           
            sudo docker pull ksrobalino/microservicio-update-owner:latest  # Cambia el nombre de la imagen

         
            sudo docker run -d --name microservicio-update-owner --env-file .env -p 7003:7003 ksrobalino/microservicio-update-owner:latest 